nginx_client_max_body_size: "2048M"
nginx_remove_default_vhost: true
nginx_vhosts:
 - listen: "80 default_server"
   server_name: "_"

   access_log: "/var/log/nginx/artifactory.access.log"
   extra_parameters: |
    location / {
        proxy_set_header Host $host:$server_port;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:8081;
        proxy_pass_header Server;
        proxy_read_timeout 90;
    }
